/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package becasuninorte;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JONATHAN
 */
public class BecasConvocatoria extends javax.swing.JFrame {

    static SQLclass query;
    String v1[] = {"id", "nombre", "cupos"};
    String v2[] = {"id", "descripción"};
    String v[] = {"id", "periodo", "fecha inicio","fecha cierre","estado"};
    String idConvTable, idBeneficioTable, periodoAca, nomBeca;

    public BecasConvocatoria(SQLclass query) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.query = query;
        convocatorias.setModel(query.query("select * from convocatoria", v));
        DefaultTableModel var=query.query("select * from beca", v1);
        
        
        var.addColumn("Seleccinado");         
        becas.setModel(var);
        becas.getColumnModel().getColumn(3).setCellEditor(becas.getDefaultEditor(Boolean.class));         
        becas.getColumnModel().getColumn(3).setCellRenderer(becas.getDefaultRenderer(Boolean.class));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        becasConv = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        becas = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        convocatorias = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        Join = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 652));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel4.setBackground(new java.awt.Color(255, 7, 11));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 7, 11));
        jPanel3.setLayout(new java.awt.BorderLayout());

        becasConv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        becasConv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                becasConvMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(becasConv);

        jPanel3.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jLabel5.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Becas de la convocatoria seleccionada");
        jPanel3.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 345, 1100, 310));

        jPanel2.setBackground(new java.awt.Color(255, 7, 11));
        jPanel2.setPreferredSize(new java.awt.Dimension(512, 309));
        jPanel2.setLayout(new java.awt.BorderLayout());

        becas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        becas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                becasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(becas);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Becas disponibles");
        jPanel2.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 0, 510, 320));

        jPanel1.setBackground(new java.awt.Color(255, 7, 11));
        jPanel1.setPreferredSize(new java.awt.Dimension(512, 309));
        jPanel1.setLayout(new java.awt.BorderLayout());

        convocatorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        convocatorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                convocatoriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(convocatorias);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Convocatorias");
        jPanel1.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 480, 320));

        Join.setText("Unir");
        Join.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JoinActionPerformed(evt);
            }
        });
        jPanel4.add(Join, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 210, 100, -1));

        getContentPane().add(jPanel4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JoinActionPerformed
        if (false) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una convocatoria y una beca");
        } else {
            if (JOptionPane.showConfirmDialog(null, "¿Confirma unir becas a la convocatoria " + periodoAca
                    + " con id=" + idConvTable + "\n el beneficio:  " + nomBeca) == 0) {
                for (int i = 0; i < becas.getModel().getRowCount(); i++) {
                    if(becas.getValueAt(i, 3)!=null){
                        String comand = "insert into pertenece_a values (" + idConvTable + "," + becas.getValueAt(i, 0) + ")";
                        query.ejecutar(comand);
                    }
                }
                String join = "select b.id, nombre, cupos from beca b inner join pertenece_a pa on (b.id = pa.id_beca)"
                + " where pa.id_convocatoria = " + idConvTable;
                becasConv.setModel(query.query(join, v1));
                
            }
        }

    }//GEN-LAST:event_JoinActionPerformed

    private void convocatoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convocatoriasMouseClicked
        int seleccionado = convocatorias.rowAtPoint(evt.getPoint());
        idConvTable = String.valueOf(convocatorias.getValueAt(seleccionado, 0));
        

        periodoAca = String.valueOf(convocatorias.getValueAt(seleccionado, 1));

        String join = "select b.id, nombre, cupos from beca b inner join pertenece_a pa on (b.id = pa.id_beca)"
                + " where pa.id_convocatoria = " + idConvTable;
        becasConv.setModel(query.query(join, v1));
    }//GEN-LAST:event_convocatoriasMouseClicked

    private void becasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_becasMouseClicked
        int seleccionado = becas.rowAtPoint(evt.getPoint());
        idBeneficioTable = String.valueOf(becas.getValueAt(seleccionado, 0));

        nomBeca = String.valueOf(becas.getValueAt(seleccionado, 1));
    }//GEN-LAST:event_becasMouseClicked

    private void becasConvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_becasConvMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_becasConvMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BecasConvocatoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BecasConvocatoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BecasConvocatoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BecasConvocatoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BecasConvocatoria(query).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Join;
    private javax.swing.JTable becas;
    private javax.swing.JTable becasConv;
    private javax.swing.JTable convocatorias;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
