/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package becasuninorte;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel Porto
 */
public class Seleccion extends javax.swing.JFrame {

    /**
     * Creates new form Seleccion
     */
    static String t;
    static SQLclass DB;
    String idConv;
    DefaultTableModel m;

    public Seleccion(SQLclass database, String texto) {
        initComponents();
        this.setLocationRelativeTo(null);
        DB = database;
        String[] v1 = {"id", "per"};
        m = DB.query("SELECT id,periodo_academico FROM convocatoria", v1);
        t = texto;

        titulo.setText("Seleccione a los " + t);

        for (int i = 0; i < m.getRowCount(); i++) {
            combo.addItem(m.getValueAt(i, 1).toString());
        }
//        switch(texto){
//            case "Preseleccionados":
//                m = DB.query("Select id,identificacion,nombre,apellido1,apellido2 FROM persona where ", v2);
//                personas.setModel(m);
//            break;
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        personas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        becas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 7, 11));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 11, 333, 37));

        personas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(personas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 143, 361, 150));

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 311, -1, -1));

        becas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        becas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                becasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(becas);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 143, 365, 150));

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Becas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Personas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Periodo acedemico de convocatoria: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboItemStateChanged(evt);
            }
        });
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        jPanel1.add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
        String[] v = {"id", "Nombre", "Cupos"};
        int index = combo.getSelectedIndex();
        idConv = m.getValueAt(index, 0).toString();
        DefaultTableModel becasT;
        String comand = "select b.id, b.nombre, b.cupos from beca b inner join pertenece_a pa on (b.id=pa.id_beca) where pa.id_convocatoria=" + idConv;
        becasT = DB.query(comand, v);
        becas.setModel(becasT);
    }//GEN-LAST:event_comboActionPerformed

    private void comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboItemStateChanged
        // TODO add your handling code here:


    }//GEN-LAST:event_comboItemStateChanged
    String idBecaTable, idBeneficioTable, NombreBeca, DesBeneficio;
    private void becasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_becasMouseClicked
        // TODO add your handling code here:
        int seleccionado = becas.rowAtPoint(evt.getPoint());
        idBecaTable = String.valueOf(becas.getValueAt(seleccionado, 0));
        NombreBeca = String.valueOf(becas.getValueAt(seleccionado, 1));
        String[] vPer = {"id", "Identificación", "Nombre", "Primer apellido", "Segundo apellido", "tipo"};
        String comand = "";
        
        switch (t) {
            case "Preseleccionados":
                comand = "SELECT p.id,p.identificacion,p.nombre,p.apellido1,p.apellido2,aa.tipo_persona FROM persona p inner join aspira_a aa on(aa.id_persona=p.id) where (aa.id_convocatoria=" + idConv + " and aa.id_beca=" + idBecaTable + " and aa.tipo_persona='Aspirante')";
                break;
            case "Candidatos":
                comand = "SELECT p.id,p.identificacion,p.nombre,p.apellido1,p.apellido2,aa.tipo_persona FROM persona p inner join aspira_a aa on(aa.id_persona=p.id) where (aa.id_convocatoria=" + idConv + " and aa.id_beca=" + idBecaTable + " and aa.tipo_persona='Preseleccionado')";
                break;
            case "Becados":
                comand = "SELECT p.id,p.identificacion,p.nombre,p.apellido1,p.apellido2,aa.tipo_persona FROM persona p inner join aspira_a aa on(aa.id_persona=p.id) where (aa.id_convocatoria=" + idConv + " and aa.id_beca=" + idBecaTable + " and aa.tipo_persona='Candidato')";
                break;
        }
        DefaultTableModel var=DB.query(comand, vPer);
        var.addColumn("seleccionado");
        personas.setModel(var);
        personas.getColumnModel().getColumn(6).setCellEditor(personas.getDefaultEditor(Boolean.class));         
        personas.getColumnModel().getColumn(6).setCellRenderer(personas.getDefaultRenderer(Boolean.class));
        

    }//GEN-LAST:event_becasMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String comand;
        String condicion="";
        switch (t) {
            case "Preseleccionados":
                condicion="'Preseleccionado'";
                break;
            case "Candidatos":
                condicion="'Candidato'";
                break;
            case "Becados":
                condicion="'Becado'";
                break;
        }
        
        for (int i = 0; i < personas.getModel().getRowCount(); i++) {
            
            if(personas.getValueAt(i, 6)!=null){
                comand = "update aspira_a set tipo_persona="+condicion+" where id_persona="+personas.getValueAt(i, 0);
                DB.ejecutar(comand);
            }
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seleccion(DB, t).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable becas;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable personas;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
